### PR TITLE
Fix the connection issues

### PR DESCRIPTION
**Pull request by kouroshD**
In this PR, we address the problem we were facing with the connections. 
When we use a machine which depends on wearables and connected by WiFi to the yarpserver, it causes problem and instability in connections.
We add a number of checks in run method, in order to check the connection to yarpserver and connection between the ports.

relevant issue: https://github.com/robotology/wearables/issues/30

### CODE REVIEW

**Comment by lrapetti** [comment]
@kouroshD if the changes still apply can you please cherry-pick the two commit relative to this issue and open the PR against the updated master branch?

**Comment by DanielePucci** [comment]
@kouroshD any news on this?

**Comment by DanielePucci** [comment]
@kouroshD any news on this?

**Comment by kouroshD** [comment]
Since, we did not have the problem since the time we were using LAN cables instead of Wi-Fi, I am not sure, if we need this PR or not anymore. What do you think @diegoferigo @lrapetti @Yeshasvitvs ? If yes, I can rebase and update the PR to merge. Otherwise, we can close this PR without merging.

**Comment by kouroshD** [comment]
> Since, we did not have the problem since the time we were using LAN cables instead of Wi-Fi, I am not sure, if we need this PR or not anymore. What do you think @diegoferigo @lrapetti @Yeshasvitvs ? If yes, I can rebase and update the PR to merge. Otherwise, we can close this PR without merging.

@diegoferigo @lrapetti @Yeshasvitvs

**Comment by diegoferigo** [comment]
I don't remember precisely what was the problem in the first place. If we do not face anymore the problem we can just close the PR. Let's wait the opinion of who actually uses the suit.

**Comment by lrapetti** [comment]
> I don't remember precisely what was the problem in the first place. If we do not face anymore the problem we can just close the PR. Let's wait the opinion of who actually uses the suit.

As stated by @kouroshD, the problem described in https://github.com/robotology/wearables/issues/30 was related to wireless connection, that was no longer investigated I think.
Anyway, if we are not sure the content of this PR would be useful for any reason, and it was not properly tested, I would avoid merging it and for me we can close the PR.

**Comment by kouroshD** [comment]
> > I don't remember precisely what was the problem in the first place. If we do not face anymore the problem we can just close the PR. Let's wait the opinion of who actually uses the suit.
> 
> As stated by @kouroshD, the problem described in #30 was related to wireless connection, that was no longer investigated I think.
> Anyway, if we are not sure the content of this PR would be useful for any reason, and it was not properly tested, I would avoid merging it and for me we can close the PR.

Since we use LAN cables, we do not have anymore this issue.  so the usability of it is in doubt. Moreover, before merging also new tests should be done after rebasing, but the test with  communication problems is not trivial and repeatable. Therefore, I close this PR without merging. If in the future, we have similar problem, we can open a new issue, and use the commits here.

**Pull request closed without merging**
