### PR TITLE
Update wrappers CMakeLists to autogenerate .ini files

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
This patch addresses https://github.com/robotology/wearables/compare/patch/remove-wrappers-plugin-ini?expand=1, and removes the manual installation of `.ini` configuration files

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Review by lrapetti — CHANGES_REQUESTED** [review]
Given that we are no longer using them, in this PR we can also clean removing the unused files [`IWearWrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IWear/iwear_wrapper.ini) and [`ixsensmvncontrol_wrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IXsensMVNControl/ixsensmvncontrol_wrapper.ini)

**Comment by Yeshasvitvs** [comment]
> Given that we are no longer using them, in this PR we can also clean removing the unused files [`IWearWrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IWear/iwear_wrapper.ini) and [`ixsensmvncontrol_wrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IXsensMVNControl/ixsensmvncontrol_wrapper.ini)

Done in https://github.com/robotology/wearables/pull/93/commits/030b49065ff4509a63408b2eb41f15e76e8536b4

**Review by lrapetti — APPROVED** [review]

**Comment by DanielePucci** [comment]
The hyperlinks in 
> Given that we are no longer using them, in this PR we can also clean removing the unused files [`IWearWrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IWear/iwear_wrapper.ini) and [`ixsensmvncontrol_wrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IXsensMVNControl/ixsensmvncontrol_wrapper.ini) 

are not working @lrapetti

**Comment by lrapetti** [comment]
> > Given that we are no longer using them, in this PR we can also clean removing the unused files [`IWearWrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IWear/iwear_wrapper.ini) and [`ixsensmvncontrol_wrapper.ini`](https://github.com/robotology/wearables/blob/master/wrappers/IXsensMVNControl/ixsensmvncontrol_wrapper.ini)
> 
> are not working @lrapetti

because the files have been in fact removed :satisfied:.
(see https://github.com/robotology/wearables/commit/030b49065ff4509a63408b2eb41f15e76e8536b4)

**Pull request merged**
