### PR TITLE
Add wearable yarp dumper application to run HDE offline

### PR DESCRIPTION
**Pull request by Yeshasvitvs**
This PR adds a yarp manager application configuration file to save Xsens suit and FTShoes wearable data through yarp data daumper, to run human dynamics estimation tests offline.

### CODE REVIEW

**Comment by lrapetti** [comment]
Is the only difference from https://github.com/robotology/wearables/blob/config/HDE-WearableDumper/app/xml/applications/WearableDevices-Dumper.xml the absence of the skin insole?

**Comment by Yeshasvitvs** [comment]
> Is the only difference from https://github.com/robotology/wearables/blob/config/HDE-WearableDumper/app/xml/applications/WearableDevices-Dumper.xml the absence of the skin insole?

Yes, I notice that often times we modify it during data collection. So, for convenience I would like to add it.

**Comment by claudia-lat** [comment]
cc @lrapetti

**Review by lrapetti — APPROVED** [review]

**Comment by Yeshasvitvs** [comment]
Thanks @lrapetti 
Merging.

**Pull request merged**
