### PR TITLE
Update CI files

### PR DESCRIPTION
**Pull request by lrapetti**
Since `AppVeyor` is no longer used (https://github.com/robotology/wearables/issues/26), I am removing the related configuration files

### CODE REVIEW

**Comment by lrapetti** [comment]
Removing also the CI support for Xenial (https://github.com/robotology/wearables/pull/74/commits/0b5b8a3bfa0ca73b7ac9b76a551e0c8f6fbce267)

**Comment by diegoferigo** [comment]
@lrapetti You also have to remove the jobs from the build matrix

https://github.com/robotology/wearables/blob/f2f63e75ec96142cd1e67ffa51471a214773b3b8/.travis.yml#L23-L24

**Comment by lrapetti** [comment]
> @lrapetti You also have to remove the jobs from the build matrix

thanks, now are removed.

**Comment by Yeshasvitvs** [comment]
Merging @lrapetti thanks

**Pull request merged**
