### PR TITLE
Implement the python bindings for the WearableData msg

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
With this PR it will be possible to get and send the WearableData message via python and thanks to [this](https://it.mathworks.com/help/matlab/matlab_external/ways-to-call-python-from-matlab.html) in MATLAB

```python
import yarp
import wearables.bindings as wearables

# create the yarp network 
network = yarp.Network()
network.init()

port = wearables.msg.BufferedPortWearableData()
port.open("/foo")

data = port.read(False)
```

On matlab
```matlab
%% Initialize the YARP Network and collect data.
clear; clc;
network = yarp.Network()
network.init()
py.importlib.import_module('wearables.bindings');
port = py.wearables.bindings.msg.BufferedPortWearableData();
port.open("/foo"); % Opening port named '/foo'

% Remember to connect the ports. Command line is the following:
% yarp connect /iFeelSuit/WearableData/data:o /foo
yarp.Network.connect('/iFeelSuit/WearableData/data:o', '/foo') 
data = port.read();
val = data.forceTorque6DSensors;
forceZ_Left = val{'iFeelSuit::ft6D::Node#1'}.data.force.z;
forceZ_Right = val{'iFeelSuit::ft6D::Node#2'}.data.force.z;
```

cc @conconman @RiccardoGrieco @lrapetti @traversaro

### CODE REVIEW

**Review by lrapetti — COMMENTED** [review]
@GiulioRomualdi could you please update the `CHANGELOG.md`

**Comment by GiulioRomualdi** [comment]
Done @lrapetti. @conconman could you please copy-paste the example in MatLab that we run this morning?

**Comment by conconman** [comment]
@GiulioRomualdi as far as I can tell, there's no timestamp associated with this data collection. That would be necessary information to have.

**Comment by GiulioRomualdi** [comment]
As far as I know, the timestamp is not streamed, @lrapetti can complement this

**Comment by lrapetti** [comment]
I confirm the timestamp is not included in the message that is streamed, you can have an idea of the content of the message by looking at the thrift https://github.com/robotology/wearables/blob/master/msgs/thrift/WearableData.thrift.

Depending on your purpose, maybe you can use the receiver timestep from your machine?

**Comment by conconman** [comment]
> I confirm the timestamp is not included in the message that is streamed, you can have an idea of the content of the message by looking at the thrift https://github.com/robotology/wearables/blob/master/msgs/thrift/WearableData.thrift.
> 
> Depending on your purpose, maybe you can use the receiver timestep from your machine?

Without spending a ton of time on this problem, I believe the `cputime` or `tic/toc` should be sufficient depending on the conditions.

**Comment by lrapetti** [comment]
@GiulioRomualdi sorry for the delay, can I proceed to merge?

**Comment by lrapetti** [comment]
One thing that seems to be missing is the test with the `WEARABLES_COMPILE_PYTHON_BINDINGS` flag `ON`, @GiulioRomualdi let me know if you can take care of adding it, otherwise I will take care.

I think after merging we should add the flag also in the`robotology-superbuild`

**Comment by RiccardoGrieco** [comment]
I would also add a reference to `WEARABLES_COMPILE_PYTHON_BINDINGS` in the README, for instance [here](also https://github.com/robotology/wearables/blob/57460c273e9012f07af9ec955758f243a7092c4f/README.md?plain=1#L43).

**Comment by GiulioRomualdi** [comment]
I updated the readme in https://github.com/robotology/wearables/pull/162/commits/10e8fa0b2923ce44fbf9d8da45a5101d5dc78e31 and I enabled the compilation of the bindings in the CI in https://github.com/robotology/wearables/pull/162/commits/706256051293326bb040e89121d9199a64c55bc6

@RiccardoGrieco and @lrapetti let me know if you are fine with the changes 😃

**Review by RiccardoGrieco — APPROVED** [review]

**Review by lrapetti — APPROVED** [review]
Thanks!

**Comment by lrapetti** [comment]
I just noticed that what I mentioned in https://github.com/robotology/wearables/pull/162#issuecomment-1228182084 regarding the `superbuild`, still needs to be addressed.

**Comment by lrapetti** [comment]
> I just noticed that what I mentioned in [#162 (comment)](https://github.com/robotology/wearables/pull/162#issuecomment-1228182084) regarding the `superbuild`, still needs to be addressed. I will take care of it

PR opened https://github.com/robotology/robotology-superbuild/pull/1259

**Pull request merged**
