### PR TITLE
Bump wearables version to 1.1.0

### PR DESCRIPTION
**Pull request by lrapetti**

### CODE REVIEW

**Review by traversaro — APPROVED** [review]

**Comment by traversaro** [comment]
Just a curiosity, don't you also have the version in the CMake ?

**Comment by traversaro** [comment]
> 
> 
> Just a curiosity, don't you also have the version in the CMake ?

Indeed, I think we need to bump also the version in https://github.com/robotology/wearables/blob/release-1.1.0/interfaces/IWear/CMakeLists.txt#L6 .

**Comment by lrapetti** [comment]
> Just a curiosity, don't you also have the version in the CMake ?

Yes actually was not there, but I think it might be useful to have it in order to be handled by dependencies. I will take care of adding it with this release.


> Indeed, I think we need to bump also the version in https://github.com/robotology/wearables/blob/release-1.1.0/interfaces/IWear/CMakeLists.txt#L6 .

I think, in origin `IWear` was supposed to have it's own versioning since it is a stand-alone interface library. In this case, however, I think keeping same versioning is better since we are maintaining a singe `CHANGELOG` for the whole repository.
What do you think @traversaro?

I took care of those changes in https://github.com/robotology/wearables/pull/95/commits/5286e2539403324c10129ec3fa6d90489095e348.

**Comment by traversaro** [comment]
I agree, let's have a single version!

**Pull request merged**
