### PR TITLE
Fix IwearRemapper when we have several ports

### PR DESCRIPTION
**Pull request by kouroshD**

### CODE REVIEW

**Review by diegoferigo — APPROVED** [review]
Thanks for formatting this file (similarly to #115). I think we should give an overall pass to the whole project since in the past few PRs have been merged without checking the style (we don't have yet a CI check and I don't follow all the development of this repo).

The fix, as discussed in detail privately, LGTM. Can you just move down the mutex to only protect the following section? Thanks :wink: 

https://github.com/robotology/wearables/blob/b91ddc5fbe23d3806cde633835efa4a333d53334/devices/IWearRemapper/src/IWearRemapper.cpp#L785-L792

**Comment by kouroshD** [comment]
> The fix, as discussed in detail privately, LGTM. Can you just move down the mutex to only protect the following section? Thanks wink

Done!

**Comment by diegoferigo** [comment]
@kouroshD can you let me know when you're done working on the PR? before merging I'd like to take advantage to update the indentation of `onRead`.

**Comment by kouroshD** [comment]
> @kouroshD can you let me know when you're done working on the PR? before merging I'd like to take advantage to update the indentation of onRead.

Yes, I am done!

**Review by lrapetti — APPROVED** [review]
Thanks @kouroshD and @diegoferigo

**Comment by diegoferigo** [comment]
Give me a second before merging, I added the last commit from the web interface but I fear that clang-format will change something.

**Comment by diegoferigo** [comment]
Indeed, good to go now.

**Pull request merged**
