### PR TITLE
Revert "remove thrift/ in include and fix compilation with YARP 3.2.101"

### PR DESCRIPTION
**Pull request by lrapetti**
This reverts https://github.com/robotology/wearables/pull/65 for fixing https://github.com/robotology/wearables/issues/56 as suggested in https://github.com/robotology/yarp/issues/2142#issuecomment-562166018

### CODE REVIEW

**Comment by lrapetti** [comment]
With this PR I also update Travis MacOS test to use `xcode10` in order to have cmake version > `3.12`

**Comment by traversaro** [comment]
Did you verified that this version compiles fine with YARP 3.3 ?

**Comment by lrapetti** [comment]
> Did you verified that this version compiles fine with YARP 3.3 ?

Isn't it the current `master`?

**Comment by traversaro** [comment]
> > Did you verified that this version compiles fine with YARP 3.3 ?
> 
> Isn't it the current `master`?

yarp-3.3 is slightly behind the current master (see https://github.com/robotology/yarp/tree/yarp-3.3) but for the purpose of this fix probably they can be considered equivalent.

**Pull request merged**
